import Head from 'next/head';
import Layout from '@/components/Layout';
import CalendarHome from './CalendarHome';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Big Plan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  )
}